sudo:
  true

language:
  php

php:
  - 5.4
  - 5.5
  - 5.6

# Build matrix options
matrix:
  include:
    - php: 5.4
      env: WP_TRAVISCI=travis:phpunit
    - php: 5.5
      env: WP_TRAVISCI=travis:phpunit
    - php: 5.6
      env: WP_TRAVISCI=travis:phpunit
  allow_failures:
    - php: 5.6
  fast_finish: true

notifications:
  email: true
